project_id = "eihbccorntsqptkhfium"

[auth]
site_url = "https://docprecos.vercel.app"
additional_redirect_urls = []
enable_signup = false

[auth.email]
enable_signup = false
enable_confirmations = true
max_frequency = "1m0s"
otp_length = 8

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true
